ALTER TABLE MEDDRA.SMQ_LIST
    ADD INDEX (smq_code);

ALTER TABLE MEDDRA.SMQ_CONTENT
    ADD INDEX (smq_code);

ALTER TABLE MEDDRA.SMQ_CONTENT
    ADD INDEX (term_code);

ALTER TABLE MEDDRA.MDHIER
    ADD INDEX (primary_soc_fg);

ALTER TABLE MEDDRA.MDHIER
    ADD INDEX (pt_code);

ALTER TABLE MEDDRA.LOW_LEVEL_TERM
    ADD INDEX (pt_code);

ALTER TABLE MEDDRA.LOW_LEVEL_TERM
    ADD INDEX (llt_name);

ALTER TABLE MEDDRA.LOW_LEVEL_TERM
    ADD INDEX (llt_code);