CREATE INDEX CUI_IDX
    ON MRCONSO (CUI);

CREATE INDEX TTY_IDX
    ON MRCONSO (TTY);

CREATE INDEX SUPPRESS_IDX
    ON MRCONSO (SUPPRESS);

CREATE INDEX SAB_IDX
    ON MRCONSO (SAB);

CREATE INDEX CODE_IDX
    ON MRCONSO (CODE);